import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MensAccessoriesService {

  constructor() { }
  mens_accessories() {
    return [
    {
      id: 501,
      image : "../../assets/images/feature1.jpg",
      title : "Van Heusen V ",
      description : "Dot Men's Poly Viscose Shawl Collar Suit ",
      price : 19.99,
      total : 19.99,
      rating :"⭐⭐⭐⭐⭐",
      brand: "gucci",
      instock : true,
      quantity : 1,
    },
    {
      id: 502,
      image : "../../assets/images/feature2.jpg",
      title : "Van Heusen Men's",
      description : "Men's Synthetic Notch Lapel Suit. ",
      price : 29.99,
      total : 29.99,
      rating :"⭐⭐⭐⭐",
      brand: "gucci",
      instock : true,
      quantity : 1,
    },
    {
      id: 503,
      image : "../../assets/images/feature3.jpg",
      title : "Van Heusen Men Suit ",
      description : "Dress Set ",
      price : 39.99,
      total : 39.99,
      rating :"⭐⭐⭐⭐⭐",
      brand: "gucci",
      instock : true,
      quantity : 1,
    },
    {
      id: 504,
      image : "../../assets/images/suit1.jpg",
      title : "Van Heusen Men ",
      description : "Business Suit Pants Set ",
      price : 19.99,
      total : 19.99,
      rating :"⭐⭐⭐⭐⭐",
      brand: "gucci",
      instock : true,
      quantity : 1,
    },
    {
      id: 505,
      image : "../../assets/images/suit2.jpg",
      title : "Van Heusen Men's Polyester",
      description : " Blend Three Piece Suit-Dress Set  ",
      price : 29.99,
      total : 29.99,
      rating :"⭐⭐⭐⭐",
      brand: "gucci",
      instock : false,
      quantity : 1,
    },
    {
      id: 506,
      image : "../../assets/images/suit3.jpg",
      title : "Van Heusen Men's  ",
      description : "Polyester Blend Three Piece Suit ",
      price : 39.99,
      total : 39.99,
      rating :"⭐⭐⭐⭐⭐",
      brand: "blackberry",
      instock : true,
      quantity : 1,
    },
    {
      id: 507,
      image : "../../assets/images/suit4.jpg",
      title : "Van Heusen ",
      description : "Men Suit ",
      price : 19.99,
      total : 19.99,
      rating :"⭐⭐⭐⭐⭐",
      brand: "gucci",
      instock : true,
      quantity : 1,
    },
    {
      id: 508,
      image : "../../assets/images/suit5.jpg",
      title : "Van Heusen Men's Rayon",
      description : "White Two Piece Suit Business Pants Set ",
      price : 29.99,
      total : 29.99,
      rating :"⭐⭐⭐⭐",
      brand: "blackberry",
      instock : true,
      quantity : 1,
    },
    {
      id: 509,
      image : "../../assets/images/suit6.jpg",
      title : "Van Heusen ",
      description : "Men Suit ",
      price : 39.99,
      total : 39.99,
      rating :"⭐⭐⭐⭐⭐",
      brand: "gucci",
      instock : true,
      quantity : 1,
    },
    {
      id: 510,
      image : "../../assets/images/suit7.jpg",
      title : "Raymond ",
      description : "Dark Grey Suit ",
      price : 19.99,
      total : 19.99,
      rating :"⭐⭐⭐⭐⭐",
      brand: "blackberry",
      instock : false,
      quantity : 1,
    },
    {
      id: 511,
      image : "../../assets/images/suit8.jpg",
      title : "Van Heusen Men's Cotton Blend ",
      description : "White Two Piece Suit Business Pants Set ",
      price : 29.99,
      total : 29.99,
      rating :"⭐⭐⭐⭐",
      brand: "van",
      instock : true,
      quantity : 1,
    },
    {
      id: 512,
      image : "../../assets/images/suit9.jpg",
      title : "Van Heusen Men Suit ",
      description : "Polyester Blend Four Piece Suit-Dress Set  ",
      price : 39.99,
      total : 39.99,
      rating :"⭐⭐⭐⭐⭐",
      quantity : 1,
      brand: "raymond",
      instock : true,
    },
  
   ]

}}
